CREATE TABLE DOCTORS(

ID_DOCTORS INT  IDENTITY(1, 1) CONSTRAINT PK_DOCTORS PRIMARY KEY,
ID_SPECIALIZATION INT CONSTRAINT DOCTORS_SPECIALIZATION FOREIGN KEY REFERENCES SPECIALIZATION (ID_SPECIALIZATION),  

ID_OFFICE INT CONSTRAINT DOCTORS_OFFICE FOREIGN KEY REFERENCES OFFICE (ID_OFFICE),
FULLNAME NVARCHAR(100),
REGIONS INT

);