CREATE TABLE OFFICE(
ID_OFFICE INT  IDENTITY(1, 1) CONSTRAINT PK_ID_OFFICE PRIMARY KEY,

ID_SPECIALIZATION INT CONSTRAINT OFFICE_SPECIALIZATION FOREIGN KEY REFERENCES SPECIALIZATION (ID_SPECIALIZATION),

OFFICENUMBER INT,
ADDRESSOFFICE NVARCHAR(100)
);
