CREATE TABLE PACIENT_DOCTORS(
ID_DOCTORS INT CONSTRAINT PACIENT_DOCTORS_DOCTORS FOREIGN KEY REFERENCES DOCTORS (ID_DOCTORS),
ID_PACIENT INT CONSTRAINT PACIENT_DOCTORS_PACIENT FOREIGN KEY REFERENCES PACIENT(ID_PACIENT)
);
