CREATE TABLE SHEDULE(
ID_SHEDULE INT  IDENTITY(1, 1) CONSTRAINT PK_ID_SHEDULES PRIMARY KEY,
ID_DOCTORS INT CONSTRAINT SHEDULE_DOCTORS FOREIGN KEY REFERENCES DOCTORS (ID_DOCTORS),
ID_SPECIALIZATION INT CONSTRAINT SHEDULE_SPECIALIZATION FOREIGN KEY REFERENCES SPECIALIZATION (ID_SPECIALIZATION),
ID_OFFICES INT CONSTRAINT SHEDULE_OFFICE FOREIGN KEY REFERENCES OFFICE (ID_OFFICE),
DATES DATE,
TIMES NVARCHAR(100)
);
